sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g spacejam
- meteor npm install
services: mongodb
script:
- spacejam test --driver-package practicalmeteor:mocha 